# Generated by Django 3.1.2 on 2020-11-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pos_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isa.tblpermit'),
        ),
    ]
