# Generated by Django 3.1.3 on 2020-12-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblpermit',
            table='permit',
        ),
    ]
