# Generated by Django 3.1.2 on 2020-11-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0002_transaction_pos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='pos_id',
            new_name='pos',
        ),
    ]
