# Generated by Django 3.1.3 on 2020-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0002_auto_20201207_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpermit',
            name='canceldate',
            field=models.CharField(blank=True, db_column='CancelDate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblpermit',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblpermit',
            name='validuntil',
            field=models.CharField(blank=True, db_column='ValidUntil', max_length=255, null=True),
        ),
    ]
