# Generated by Django 3.1.2 on 2020-11-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0003_auto_20201116_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='isa.tblpermit'),
        ),
    ]
