# Generated by Django 3.1.3 on 2020-12-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0003_auto_20201207_1539'),
    ]

    operations = [


    ]
