# Generated by Django 3.1.3 on 2020-12-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0006_transactionzeroamount_time_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionzeroamount',
            name='time_stay',
        ),
    ]
