# Generated by Django 3.1.3 on 2021-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0008_transactionzeroamount_time_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpermit',
            name='accred',
        ),
    ]
